// One-off import of manually-verified researcher entries (no API calls —
// this data was verified by the user directly, not generated by this app).
// Run with: npx tsx scripts/seed-researchers.ts

import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";

const prisma = new PrismaClient();

const ENTRIES = [
  {
    name: "Oliver Fringer",
    university: "Stanford University",
    department: "Civil and Environmental Engineering",
    email: "fringer@stanford.edu",
    verificationSources: "Stanford CEE directory listing",
  },
  {
    name: "Sarah Fletcher",
    university: "Stanford University",
    department: "Civil and Environmental Engineering",
    email: "sfletcher@stanford.edu",
    facultyWebsite: "https://waterinthewest.stanford.edu",
    notes: "Office: Y2E2 Building, Room 169, 473 Via Ortega, Stanford",
    verificationSources: "Official Stanford \"Water in the West\" program page",
  },
  {
    name: "Tina Chow",
    university: "UC Berkeley",
    department: "Civil and Environmental Engineering",
    email: "tinakc@berkeley.edu",
    verificationSources: "Her official EFMH group page at Berkeley",
  },
  {
    name: "Stefano Schiavon",
    university: "UC Berkeley",
    department: "Architecture (Center for the Built Environment)",
    email: "schiavon@berkeley.edu",
    verificationSources: "His official Center for the Built Environment page",
  },
  {
    name: "Tsachy Weissman",
    university: "Stanford University",
    department: "Electrical Engineering",
    email: "tsachy@stanford.edu",
    verificationSources: "His official Stanford homepage",
  },
  {
    name: "H. Jane Bae",
    university: "California Institute of Technology",
    department: "GALCIT (Graduate Aerospace Laboratories)",
    email: "jbae@caltech.edu",
    verificationSources: "Her official Bae Research Group people page",
    notes:
      "spontes@caltech.edu belongs to Sarah Pontes, her admin assistant — do not use that address",
  },
  {
    name: "Michael F. Howland",
    university: "MIT",
    department: "Civil and Environmental Engineering",
    title: "Assistant Professor (Jeffrey Cheah Career Development / Edgerton)",
    email: "mhowland@mit.edu",
    facultyWebsite: "https://cee.mit.edu/people_individual/michael-f-howland/",
    labWebsite: "https://www.howlandlab.com",
    fieldOfResearch: "Environmental Fluid Mechanics / Wind Energy",
    researchSummary:
      "His group studies environmental fluid mechanics and the modeling, optimization, and control of renewable and efficient energy systems, at the intersection of fluid mechanics, weather and climate modeling, uncertainty quantification, and optimization, using simulations, lab and field experiments.",
    recentProjects:
      "Co-leads the MIT Climate Grand Challenge project on preparing for weather and climate extremes; ONR Young Investigator Award (2024) on marine boundary layer turbulence over waves; wake steering for wind farm power optimization",
    highSchoolFriendliness: "UNKNOWN",
    undergradMentoring:
      "Yes — his lab's openings page says they seek motivated MIT undergraduates for UROPs in renewable energy and fluid dynamics",
    outreachScore: 8,
    responseProbability: "High",
    notes:
      "Openings page explicitly invites interested students to contact him directly; young lab, actively recruiting, atmospheric-flow focus is a strong match",
    verificationSources: "MIT CEE official page and his lab's contact page",
  },
  {
    name: "Brian Stone Jr.",
    university: "Georgia Institute of Technology",
    department: "School of City and Regional Planning",
    title: "Professor; Director, Urban Climate Lab",
    email: "stone@gatech.edu",
    facultyWebsite: "https://planning.gatech.edu/people/brian-stone",
    labWebsite: "https://urbanclimate.gatech.edu",
    fieldOfResearch: "Urban Heat / Climate Adaptation",
    researchSummary:
      "Stone's research focuses on the spatial drivers of urban environmental phenomena, with an emphasis on urban-scale climate change, supported by NSF, CDC, and EPA. His lab has published on thermal impacts of built and vegetated environments on local microclimates.",
    recentProjects:
      "Urban heat island mitigation and public health response; his lab's work informed Atlanta's new cool roofing ordinance; author of Radical Adaptation (Cambridge, 2024)",
    highSchoolFriendliness: "UNKNOWN",
    undergradMentoring: "UNKNOWN",
    outreachScore: 7,
    responseProbability: "Medium-High",
    notes:
      "Closest topical match to an inland-East-Bay urban heat project — heat mitigation, ventilation, urban form; lab director (slight deduction), lab work featured on NPR and Last Week Tonight",
    verificationSources: "Georgia Tech official research directory",
  },
  {
    name: "Jan Kleissl",
    university: "UC San Diego",
    department: "Mechanical and Aerospace Engineering",
    title: "Professor; Director, Center for Energy Research",
    email: "jkleissl@ucsd.edu",
    facultyWebsite: "https://jacobsschool.ucsd.edu/people/profile/jan-kleissl",
    labWebsite: "http://maeresearch.ucsd.edu/kleissl/",
    fieldOfResearch: "Urban Meteorology / Solar Energy / Building Energy",
    researchSummary:
      "Kleissl researches the interaction of weather with engineering systems — buildings and their energy use, solar power systems, and irrigated lands — and developed the first building energy model coupled with urban-canyon weather processes and urban fluid mechanics via large-eddy simulation. His group has studied how reflective pavements affect building cooling loads and canopy air temperatures.",
    recentProjects:
      "NSF-funded DER Connect testbed for grid integration of renewables; solar forecasting with sky imagers; reflective pavement and urban surface studies; EV smart charging",
    highSchoolFriendliness:
      "Yes — his official page lists K-12 environmental education with solar energy lesson plans through the UCSD Global TIES program",
    undergradMentoring:
      "Yes — teaches the undergraduate MAE126A lab course, and his page states student mentoring is his priority, with students winning NASA and NSF fellowships",
    outreachScore: 8,
    responseProbability: "High",
    notes:
      "His urban-canyon fluid mechanics and reflective-surface work overlaps directly with urban heat + hydro/aerodynamics; center director (slight deduction) offset by explicit mentoring emphasis",
    verificationSources: "His official UCSD page",
  },
  {
    name: "Aaswath Raman",
    university: "UCLA",
    department: "Materials Science and Engineering",
    title: "Associate Professor; Vice Chair for Undergraduate Education",
    email: "aaswath@ucla.edu",
    facultyWebsite: "https://samueli.ucla.edu/people/aaswath-raman/",
    labWebsite: "http://www.aaswathraman.com",
    fieldOfResearch: "Radiative Cooling / Thermal Photonics",
    researchSummary:
      "The Raman lab studies how light and heat interact with metamaterials and nanoscale optical structures, pioneering radiative sky cooling — including the first demonstration of daytime radiative cooling — with applications from building-scale cooling to energy systems.",
    recentProjects:
      "2025 Nature Sustainability paper on efficient outdoor thermal comfort via radiant cooling and infrared-reflective walls; NSF CAREER (2022); DARPA Director's Fellowship (2023); part of a multidisciplinary UCLA team addressing extreme heat in the City of Los Angeles; superwhite reflective paints for buildings",
    highSchoolFriendliness: "UNKNOWN",
    undergradMentoring:
      "Likely strong — he serves as Vice Chair for Undergraduate Education for his department (formal high-school evidence: UNKNOWN)",
    outreachScore: 7,
    responseProbability: "Medium-High",
    notes:
      "Passive cooling structures are literally his lab's signature — the most direct fit for evaporative/passive cooling concepts; moderately high-profile (TED speaker), so personalize any outreach heavily",
    verificationSources:
      "His official UCLA profile (invites students to send a CV and statement of interest to his email)",
  },
  {
    name: "Qi Li",
    university: "Cornell University",
    department: "Civil and Environmental Engineering",
    title: "Assistant Professor",
    email: "ql56@cornell.edu",
    facultyWebsite: "https://fellows.atkinson.cornell.edu/view.php?NetID=ql56",
    labWebsite: "https://liresearch.cee.cornell.edu",
    fieldOfResearch: "Boundary Layer Turbulence / Urban Heat Island",
    researchSummary:
      "Her research coalesces around the physical dynamics of the lower atmosphere and hydrologic processes in the built environment, studying flows and scalar transfer in the atmospheric boundary layer and how land-atmosphere interactions affect the hydrologic cycle, in both built and natural environments.",
    recentProjects:
      "NSF Early CAREER Award (2022) for work on urban heat island and boundary-layer turbulence; lab studies impacts of urban form on canopy flows, precipitation, and mesoscale modeling; multi-scale surface heterogeneity effects on urban atmospheric transport",
    highSchoolFriendliness: "UNKNOWN",
    undergradMentoring: "UNKNOWN",
    outreachScore: 8,
    responseProbability: "High",
    notes:
      "Her lab site explicitly invites students with \"a solid quantitative background\" interested in environmental fluid mechanics/urban heat to email her directly — near-perfect topical match",
    verificationSources: "Cornell CEE official faculty directory and her own lab site",
  },
  {
    name: "Branko Kerkez",
    university: "University of Michigan",
    department: "Civil and Environmental Engineering",
    title: "Arthur F. Thurnau Professor; Assoc. Chair for Research",
    email: "bkerkez@umich.edu",
    facultyWebsite: "https://cee.engin.umich.edu/people/kerkez-branko/",
    verificationSources: "Official Michigan CEE faculty page",
  },
  {
    name: "Grace X. Gu",
    university: "UC Berkeley",
    department: "Mechanical Engineering",
    title: "Associate Professor",
    email: "ggu@berkeley.edu",
    facultyWebsite: "https://me.berkeley.edu/people/grace-x-gu/",
    labWebsite: "https://gu.berkeley.edu/people/",
    notes:
      "Her lab's program typically only accepts college students and above — treat cold email outreach as a last resort, not the primary path",
    verificationSources: "Official Berkeley ME faculty page and her lab's people page",
  },
  {
    name: "Alice M. Agogino",
    university: "UC Berkeley",
    department: "Mechanical Engineering",
    email: "agogino@berkeley.edu",
    facultyWebsite: "https://me.berkeley.edu/people/alice-m-agogino/",
    verificationSources: "Official Berkeley ME faculty page",
  },
  {
    name: "Hannah Stuart",
    university: "UC Berkeley",
    department: "Mechanical Engineering",
    email: "hstuart@berkeley.edu",
    facultyWebsite: "https://me.berkeley.edu/people/hannah-stuart/",
    verificationSources: "Official Berkeley ME faculty page",
  },
  {
    name: "David L. Sedlak",
    university: "UC Berkeley",
    department: "Civil and Environmental Engineering",
    email: "sedlak@ce.berkeley.edu",
    facultyWebsite: "https://ce.berkeley.edu/people/faculty/sedlak",
    fieldOfResearch: "Environmental Engineering",
    verificationSources: "Official Berkeley CEE faculty page",
  },
  {
    name: "Kara L. Nelson",
    university: "UC Berkeley",
    department: "Civil and Environmental Engineering",
    email: "karanelson@berkeley.edu",
    facultyWebsite: "https://ce.berkeley.edu/people/faculty/nelson",
    fieldOfResearch: "Environmental Engineering",
    verificationSources: "Official Berkeley CEE faculty page",
  },
  {
    name: "Joshua Apte",
    university: "UC Berkeley",
    department: "Civil and Environmental Engineering",
    email: "apte@berkeley.edu",
    facultyWebsite: "https://ce.berkeley.edu/people/faculty/jsapte",
    fieldOfResearch: "Environmental Engineering (mostly air quality)",
    verificationSources: "Official Berkeley CEE faculty page",
  },
  {
    name: "Mark W. Mueller",
    university: "UC Berkeley",
    department: "Mechanical Engineering",
    email: "mwm@berkeley.edu",
    facultyWebsite: "https://me.berkeley.edu/people/mark-w-mueller/",
    verificationSources: "Official Berkeley ME faculty page",
  },
  {
    name: "Koushil Sreenath",
    university: "UC Berkeley",
    department: "Mechanical Engineering",
    email: "koushils@berkeley.edu",
    facultyWebsite: "https://me.berkeley.edu/people/koushil-sreenath/",
    verificationSources: "Official Berkeley ME faculty page",
  },
  {
    name: "Aydogan Ozcan",
    university: "UCLA",
    department: "Electrical & Computer Engineering",
    email: "ozcan@ee.ucla.edu",
    fieldOfResearch: "AI, computational imaging, biomedical devices",
    notes: "Large interdisciplinary lab with many student researchers",
    verificationSources: "Provided directly by user",
  },
  {
    name: "Mona Jarrahi",
    university: "UCLA",
    department: "Electrical & Computer Engineering",
    email: "mjarrahi@ee.ucla.edu",
    fieldOfResearch: "Terahertz electronics, biomedical imaging, wireless sensing",
    notes: "Large engineering lab, mentors many students",
    verificationSources: "Provided directly by user",
  },
  {
    name: "Long Cai",
    university: "Caltech",
    department: "Biology & Biological Engineering",
    email: "lcai@caltech.edu",
    fieldOfResearch: "Spatial genomics, single-cell biology",
    notes: "Medium-sized lab with interdisciplinary projects",
    verificationSources: "Provided directly by user",
  },
];

async function main() {
  let created = 0;
  let skipped = 0;

  for (const entry of ENTRIES) {
    const existing = await prisma.researcherDatabase.findFirst({
      where: { name: entry.name, university: entry.university },
    });
    if (existing) {
      console.log(`skip (already have): ${entry.name}`);
      skipped++;
      continue;
    }
    await prisma.researcherDatabase.create({ data: entry });
    console.log(`added: ${entry.name} — ${entry.university}`);
    created++;
  }

  console.log(`\nDone. ${created} added, ${skipped} skipped.`);
  await prisma.$disconnect();
}

main();
